mod converter;
pub mod error;
mod verify;

use substrate_bn::Fr;

use alloc::vec::Vec;
use sha2::{Digest, Sha256};

use crate::{decode_zkm_vkey_hash, error::Error, hash_public_inputs};
pub(crate) use converter::{load_groth16_proof_from_bytes, load_groth16_verifying_key_from_bytes};
pub(crate) use verify::*;

use error::Groth16Error;

#[cfg(feature = "ark")]
use crate::ArkGroth16Error;
#[cfg(feature = "ark")]
use ark_bn254::Bn254;
#[cfg(feature = "ark")]
use ark_groth16::{r1cs_to_qap::LibsnarkReduction, Groth16};
#[cfg(feature = "ark")]
use zkm_sdk::ZKMProofWithPublicValues;
#[cfg(feature = "ark")]
pub mod ark_converter;

/// A verifier for Groth16 zero-knowledge proofs.
#[derive(Debug)]
pub struct Groth16Verifier;
impl Groth16Verifier {
    /// Verifies a Ziren Groth16 proof, as generated by the Ziren SDK.
    ///
    /// # Arguments
    ///
    /// * `proof` - The proof bytes.
    /// * `public_inputs` - The Ziren public inputs.
    /// * `zkm_vkey_hash` - The Ziren vkey hash.
    ///   This is generated in the following manner:
    ///
    /// ```ignore
    /// use zkm_sdk::ProverClient;
    /// let client = ProverClient::new();
    /// let (pk, vk) = client.setup(ELF);
    /// let zkm_vkey_hash = vk.bytes32();
    /// ```
    /// * `groth16_vk` - The Groth16 verifying key bytes.
    ///   Usually this will be the [`static@crate::GROTH16_VK_BYTES`] constant, which is the Groth16
    ///   verifying key for the current Ziren version.
    ///
    /// # Returns
    ///
    /// A success [`Result`] if verification succeeds, or a [`Groth16Error`] if verification fails.
    pub fn verify(
        proof: &[u8],
        zkm_public_inputs: &[u8],
        zkm_vkey_hash: &str,
        groth16_vk: &[u8],
    ) -> Result<(), Groth16Error> {
        // Hash the vk and get the first 4 bytes.
        let groth16_vk_hash: [u8; 4] = Sha256::digest(groth16_vk)[..4]
            .try_into()
            .map_err(|_| Groth16Error::GeneralError(Error::InvalidData))?;

        // Check to make sure that this proof was generated by the groth16 proving key corresponding to
        // the given groth16_vk.
        //
        // Ziren prepends the raw Groth16 proof with the first 4 bytes of the groth16 vkey to
        // facilitate this check.
        if groth16_vk_hash != proof[..4] {
            return Err(Groth16Error::Groth16VkeyHashMismatch);
        }

        let zkm_vkey_hash = decode_zkm_vkey_hash(zkm_vkey_hash)?;

        Self::verify_gnark_proof(
            &proof[4..],
            &[zkm_vkey_hash, hash_public_inputs(zkm_public_inputs)],
            groth16_vk,
        )
    }

    #[cfg(feature = "ark")]
    pub fn ark_verify(
        proof_with_pub_values: &ZKMProofWithPublicValues,
        vkey_hash: &str,
        groth16_vk: &[u8],
    ) -> Result<bool, ArkGroth16Error> {
        let ark_proof = crate::convert_ark(proof_with_pub_values, vkey_hash, groth16_vk)?;

        Groth16::<Bn254, LibsnarkReduction>::verify_proof(
            &ark_proof.groth16_vk,
            &ark_proof.proof,
            &ark_proof.public_inputs,
        )
        .map_err(|_| ArkGroth16Error::ProofVerificationFailed)
    }

    /// Verifies a Gnark Groth16 proof using raw byte inputs.
    ///
    /// WARNING: if you're verifying a Ziren proof, you should use [`verify`] instead.
    /// This is a lower-level verification method that works directly with raw bytes rather than
    /// the Ziren SDK's data structures.
    ///
    /// # Arguments
    ///
    /// * `proof` - The raw Groth16 proof bytes (without the 4-byte vkey hash prefix)
    /// * `public_inputs` - The public inputs to the circuit
    /// * `groth16_vk` - The Groth16 verifying key bytes
    ///
    /// # Returns
    ///
    /// A [`Result`] containing unit `()` if the proof is valid,
    /// or a [`Groth16Error`] if verification fails.
    ///
    /// # Note
    ///
    /// This method expects the raw proof bytes without the 4-byte vkey hash prefix that
    /// [`verify`] checks. If you have a complete proof with the prefix, use [`verify`] instead.    
    pub fn verify_gnark_proof(
        proof: &[u8],
        public_inputs: &[[u8; 32]],
        groth16_vk: &[u8],
    ) -> Result<(), Groth16Error> {
        let proof = load_groth16_proof_from_bytes(proof).unwrap();
        let groth16_vk = load_groth16_verifying_key_from_bytes(groth16_vk).unwrap();

        let public_inputs =
            public_inputs.iter().map(|input| Fr::from_slice(input).unwrap()).collect::<Vec<_>>();
        verify_groth16_algebraic(&groth16_vk, &proof, &public_inputs)
    }
}
